# Generated by Django 5.0.1 on 2024-01-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('store_manager', 'Store manager'), ('senior_management', 'Senior management'), ('Stock_handler', 'Stock handler')], max_length=150, null=True),
        ),
    ]
