# Generated by Django 5.0.1 on 2024-01-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_log_delete_routerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='category_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='emei',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
