# Generated by Django 5.0.1 on 2024-01-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_log_category_name_log_emei'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='instance_id',
            field=models.IntegerField(null=True),
        ),
    ]
