# Generated by Django 5.0.1 on 2024-01-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='action',
            name='imei2',
        ),
        migrations.AddField(
            model_name='action',
            name='router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.router'),
        ),
        migrations.AddField(
            model_name='action',
            name='router2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imei2', to='main.router'),
        ),
    ]
