# Generated by Django 5.0.1 on 2024-01-26 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_action_imei_remove_action_imei2_action_router_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='store',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.store'),
        ),
    ]
