# Generated by Django 5.0.1 on 2024-01-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_action_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.store'),
        ),
    ]
