# Generated by Django 5.0.1 on 2024-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_action_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
