# Generated by Django 5.0.1 on 2024-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
