# Generated by Django 5.0.1 on 2024-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_action_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
