# Generated by Django 5.0.1 on 2024-02-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_action_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alert_on',
            field=models.IntegerField(default=50),
        ),
    ]
