# Generated by Django 5.0.1 on 2024-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_category_alert_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='alert_on',
            field=models.IntegerField(default=50),
        ),
    ]
