# Generated by Django 5.0.1 on 2024-02-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_store_alert_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='emei',
            new_name='serial_number',
        ),
    ]
