# Generated by Django 5.0.1 on 2024-02-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_emei_log_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='serial_number',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
